### ISSUE TITLE
Decide on parallelization and rateLimiting parameters for actual deployment

### ISSUE THREAD

**Issue by ldgriswold** [defenseunicorns-partnerships/argo-wf-zarf#74]
Modify `values.yaml` to include the following fields under `controller`:
```yaml
  # -- parallelism dictates how many workflows can be running at the same time  
  parallelism:
  # -- Globally limits the rate at which pods are created.
  # This is intended to mitigate flooding of the Kubernetes API server by workflows with a large amount of
  # parallel nodes.
  resourceRateLimit: {}
    # limit: 10
    # burst: 1
```
